import { Fade } from '@/components/motion';
import { CheckCircle2, Layers3, Sparkles, Zap } from '@/components/icons';

export default function About() {
  return <div className="section-pad pt-32"><div className="container"><Fade><p className="text-xs uppercase tracking-[.25em] text-cyan-300">About me</p><h1 className="mt-3 max-w-4xl text-5xl font-black tracking-[-.04em] md:text-6xl">Passionate about building <span className="text-gradient">digital solutions.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">I enjoy taking ambiguous ideas, breaking them into useful systems and shipping polished experiences. My sweet spot sits between engineering, product thinking and automation.</p></Fade>
  <div className="mt-14 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Fade className="card rounded-3xl p-7 md:p-9"><h2 className="text-xl font-bold">My journey</h2><div className="mt-8 space-y-8 border-l border-cyan-400/20 pl-7">{[['2023 — Present','Full Stack Developer','Building web applications using Next.js, React, Node.js and Supabase.'],['2021 — 2023','Frontend Developer','Created responsive interfaces and reusable UI systems.'],['2019 — 2021','Computer Science','Built the fundamentals: software development, databases and algorithms.']].map(([date,title,text])=><div key={date} className="relative"><span className="absolute -left-[36px] top-1.5 h-3 w-3 rounded-full border-2 border-cyan-300 bg-slate-950"/><div className="text-xs text-cyan-300">{date}</div><div className="mt-1 font-semibold">{title}</div><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></Fade>
  <Fade delay={.08} className="card rounded-3xl p-7 md:p-9"><h2 className="text-xl font-bold">How I work</h2><div className="mt-7 space-y-5">{[['Build for users','Solve the real problem, not just the feature.'],['Keep learning','Technology evolves, so I do too.'],['Be reliable','Clean code, clear communication, predictable delivery.'],['Work together','The best products come from collaboration.']].map(([a,b])=><div key={a} className="flex gap-3"><div className="mt-0.5 text-cyan-300"><CheckCircle2 size={18}/></div><div><div className="font-medium">{a}</div><p className="mt-1 text-sm text-slate-500">{b}</p></div></div>)}</div></Fade></div>
  <div className="mt-6 grid gap-5 sm:grid-cols-3"><P icon={<Layers3/>} title="Systems" text="Architecture that can evolve."/><P icon={<Sparkles/>} title="Craft" text="Details that make products feel premium."/><P icon={<Zap/>} title="Speed" text="From idea to usable product quickly."/></div>
  </div></div>;
}
function P({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <Fade className="card card-hover rounded-2xl p-6"><div className="mb-4 text-violet-300">{icon}</div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></Fade>}
