import Link from 'next/link';
import { ArrowRight, Download, Github, Linkedin, Code2, Cloud, BrainCircuit, ArrowUpRight } from '@/components/icons';
import { projects } from '@/lib/data';
import { Fade, ScaleIn } from '@/components/motion';
import { ProjectCard } from '@/components/project-card';

export default function Home() {
  return <><section className="relative overflow-hidden pt-32 md:pt-40">
    <div className="glow left-[5%] top-20 h-72 w-72 bg-cyan-500"/><div className="glow right-[8%] top-10 h-96 w-96 bg-violet-600"/>
    <div className="container grid-bg relative rounded-[2rem] border border-white/5 px-5 py-14 md:px-12 md:py-20">
      <div className="grid items-center gap-14 lg:grid-cols-[1.1fr_.9fr]"><Fade><div>
        <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/5 px-3 py-1.5 text-xs text-cyan-200"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-cyan-300"/> Full Stack Developer</div>
        <h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">I build digital products that solve <span className="text-gradient">real problems.</span></h1>
        <p className="mt-7 max-w-2xl text-base leading-7 text-slate-400 md:text-lg">I’m a product-minded developer focused on modern web apps, AI workflows and automation — turning complex ideas into clean, scalable experiences.</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link href="/projects" className="btn-primary inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold">View My Work <ArrowRight size={16}/></Link><a href="#" className="btn-ghost inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold text-slate-200"><Download size={16}/> Download Resume</a></div>
        <div className="mt-8 flex items-center gap-5 text-slate-500"><a href="https://github.com/tejtechsolo" target="_blank" rel="noreferrer" className="hover:text-white"><Github size={18}/></a><Linkedin size={18}/><span className="h-4 w-px bg-white/10"/><span className="text-xs">Available for selected projects</span></div>
      </div></Fade>
      <ScaleIn><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-8 rounded-full bg-gradient-to-r from-cyan-500/15 to-violet-600/15 blur-3xl"/><div className="relative aspect-square rounded-[2rem] border border-cyan-300/15 bg-gradient-to-br from-cyan-400/10 via-slate-900 to-violet-500/10 p-4 shadow-2xl shadow-cyan-500/10"><div className="grid h-full place-items-center overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#061224]"><div className="text-center"><div className="mx-auto grid h-40 w-40 place-items-center rounded-full border border-cyan-300/30 bg-gradient-to-br from-cyan-400/20 to-violet-500/20 text-5xl font-black text-white/90 shadow-[0_0_70px_rgba(34,211,238,.18)]">TS</div><div className="mt-6 font-semibold">TechSolo</div><div className="mt-1 text-sm text-slate-500">Code • AI • Automation</div></div></div><div className="absolute -right-4 top-10 rounded-xl border border-white/10 bg-slate-950/90 px-3 py-2 text-xs shadow-xl"><span className="text-cyan-300">✦</span> Building next.js apps</div><div className="absolute -left-4 bottom-10 rounded-xl border border-white/10 bg-slate-950/90 px-3 py-2 text-xs shadow-xl">Ideas → <span className="text-violet-300">impact</span></div></div></div></ScaleIn></div>
      <div className="mt-16 grid grid-cols-2 border-t border-white/10 pt-8 sm:grid-cols-4"><Stat n="6+" t="Projects shipped"/><Stat n="10+" t="Technologies"/><Stat n="5+" t="Product ideas"/><Stat n="100%" t="Builder mindset"/></div>
    </div>
  </section>
  <section className="section-pad"><div className="container"><Fade><div className="mb-10 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Selected work</p><h2 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Products I’ve built.</h2></div><Link href="/projects" className="hidden items-center gap-1 text-sm text-slate-400 hover:text-white sm:flex">View all <ArrowUpRight size={15}/></Link></div></Fade><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{projects.slice(0,3).map((p,i)=><ProjectCard key={p.slug} project={p} index={i}/>)}</div></div></section>
  <section className="section-pad border-y border-white/5 bg-slate-950/40"><div className="container"><Fade><div className="grid gap-5 md:grid-cols-3"><Mini icon={<Code2/>} title="Web Engineering" text="Fast, accessible interfaces and robust full-stack foundations."/><Mini icon={<BrainCircuit/>} title="AI Products" text="Practical AI features, chat experiences and automation workflows."/><Mini icon={<Cloud/>} title="Cloud & DevOps" text="Deployment, CI/CD, integrations and production-minded architecture."/></div></Fade></div></section></>;
}
function Stat({n,t}:{n:string;t:string}){return <div className="py-2 text-center sm:text-left"><div className="text-2xl font-bold">{n}</div><div className="mt-1 text-xs text-slate-500">{t}</div></div>}
function Mini({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="card card-hover rounded-2xl p-6"><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300">{icon}</div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
